const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat nam at lectus urna duis convallis convallis tellus. Quam nulla porttitor massa id neque aliquam vestibulum. Non diam phasellus vestibulum lorem sed risus ultricies. Ut tellus elementum sagittis vitae. In eu mi bibendum neque. Elementum integer enim neque volutpat ac tincidunt vitae. In metus vulputate eu scelerisque. Urna cursus eget nunc scelerisque viverra mauris in. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Ultrices dui sapien eget mi proin sed libero. Netus et malesuada fames ac. Tempus egestas sed sed risus pretium quam.`,
  `Sed ullamcorper morbi tincidunt ornare massa eget. Tincidunt arcu non sodales neque sodales ut etiam sit. Diam quis enim lobortis scelerisque fermentum. Massa tincidunt nunc pulvinar sapien et ligula. Nunc id cursus metus aliquam eleifend mi. Vivamus arcu felis bibendum ut tristique et egestas. Turpis in eu mi bibendum. Vulputate sapien nec sagittis aliquam malesuada bibendum. Nulla facilisi morbi tempus iaculis. Etiam sit amet nisl purus in. Eget lorem dolor sed viverra ipsum nunc aliquet. Tincidunt tortor aliquam nulla facilisi cras. Ac feugiat sed lectus vestibulum. Euismod lacinia at quis risus. Bibendum est ultricies integer quis auctor. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum.`,
  `Nibh venenatis cras sed felis eget velit aliquet. Eget mauris pharetra et ultrices neque ornare aenean. Elementum sagittis vitae et leo. Eu facilisis sed odio morbi quis commodo odio. In dictum non consectetur a erat. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Vitae purus faucibus ornare suspendisse sed. Duis tristique sollicitudin nibh sit amet commodo nulla. Mi quis hendrerit dolor magna eget est. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Sit amet nisl purus in mollis. Pellentesque nec nam aliquam sem et tortor consequat id. Consectetur purus ut faucibus pulvinar. Orci porta non pulvinar neque. Turpis tincidunt id aliquet risus feugiat in ante.`,
  `Diam volutpat commodo sed egestas egestas. Viverra nam libero justo laoreet sit. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Vulputate odio ut enim blandit volutpat maecenas volutpat. Elementum integer enim neque volutpat. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Id semper risus in hendrerit gravida rutrum quisque non. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Malesuada fames ac turpis egestas. Diam vel quam elementum pulvinar etiam non quam lacus. Pretium vulputate sapien nec sagittis aliquam malesuada. Non consectetur a erat nam at lectus urna duis convallis. Amet nisl suscipit adipiscing bibendum est. Arcu dictum varius duis at consectetur. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum.`,
  `Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Fames ac turpis egestas integer. Dictumst quisque sagittis purus sit amet. Et sollicitudin ac orci phasellus egestas. Odio ut enim blandit volutpat maecenas volutpat. Dui sapien eget mi proin sed libero enim. Laoreet sit amet cursus sit amet dictum sit amet justo. Fames ac turpis egestas maecenas pharetra. Ultricies integer quis auctor elit sed vulputate. At auctor urna nunc id cursus metus aliquam eleifend mi. Nec feugiat nisl pretium fusce id. Neque sodales ut etiam sit. Gravida dictum fusce ut placerat orci nulla pellentesque. Pharetra et ultrices neque ornare aenean.`,
  `Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Arcu odio ut sem nulla pharetra diam sit amet. Quis enim lobortis scelerisque fermentum dui faucibus. Sit amet justo donec enim diam. Eu non diam phasellus vestibulum lorem. Amet volutpat consequat mauris nunc congue nisi vitae. Lectus mauris ultrices eros in cursus turpis massa tincidunt. Dis parturient montes nascetur ridiculus mus. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Morbi non arcu risus quis. Egestas pretium aenean pharetra magna ac placerat vestibulum. Turpis massa sed elementum tempus.`,
  `Diam in arcu cursus euismod quis viverra nibh. Integer feugiat scelerisque varius morbi enim nunc. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Ut aliquam purus sit amet luctus venenatis. Volutpat commodo sed egestas egestas. Lacus sed turpis tincidunt id aliquet risus feugiat. Lectus vestibulum mattis ullamcorper velit. Magna sit amet purus gravida quis blandit turpis cursus. Ultricies leo integer malesuada nunc vel risus.`,
  `Consectetur adipiscing elit pellentesque habitant morbi tristique. Proin sed libero enim sed faucibus turpis. In nulla posuere sollicitudin aliquam ultrices sagittis orci. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Facilisis volutpat est velit egestas dui. Sit amet justo donec enim diam vulputate ut. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Orci phasellus egestas tellus rutrum. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Purus semper eget duis at tellus at urna condimentum mattis. Amet nisl purus in mollis. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Feugiat scelerisque varius morbi enim nunc faucibus. Consequat ac felis donec et odio. Egestas quis ipsum suspendisse ultrices. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Vitae congue mauris rhoncus aenean vel elit scelerisque.`,
  `Mauris rhoncus aenean vel elit scelerisque mauris. Vitae sapien pellentesque habitant morbi tristique. Sit amet est placerat in egestas erat imperdiet sed. Vulputate enim nulla aliquet porttitor lacus. Vulputate eu scelerisque felis imperdiet. Laoreet sit amet cursus sit. Odio aenean sed adipiscing diam donec adipiscing. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Lacus vel facilisis volutpat est velit egestas. Adipiscing at in tellus integer. Nisl suscipit adipiscing bibendum est ultricies. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Nulla aliquet porttitor lacus luctus accumsan tortor. Id aliquet lectus proin nibh nisl condimentum id venenatis. Cras tincidunt lobortis feugiat vivamus at. Elementum nisi quis eleifend quam adipiscing vitae proin.`,
  `Enim sit amet venenatis urna cursus eget. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Aenean sed adipiscing diam donec adipiscing. Vestibulum lectus mauris ultrices eros in. Sed felis eget velit aliquet sagittis id consectetur purus. Risus ultricies tristique nulla aliquet enim. Accumsan sit amet nulla facilisi morbi. Ridiculus mus mauris vitae ultricies leo. Est sit amet facilisis magna etiam. Mattis nunc sed blandit libero volutpat sed. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in.`,
  `Est placerat in egestas erat imperdiet sed euismod. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Eros in cursus turpis massa tincidunt dui ut ornare. Feugiat nisl pretium fusce id velit ut. Vitae congue eu consequat ac felis. Vel pretium lectus quam id leo in vitae turpis. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Eu volutpat odio facilisis mauris sit amet massa vitae tortor. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Varius quam quisque id diam vel quam elementum pulvinar. Eget egestas purus viverra accumsan in nisl. Tellus cras adipiscing enim eu turpis egestas. Sed enim ut sem viverra aliquet eget sit amet tellus. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend.`,
];

const form = document.querySelector(".lorem-form");
const amount = document.getElementById("amount");
const result = document.querySelector(".lorem-text");

function generateParagraph(e) {
  e.preventDefault();
  const value = amount.value;
  const random = Math.floor(Math.random() * text.length);

  if (value) {
    let selectedText = text.slice(0, value);
    selectedText = selectedText
      .map((item) => {
        return `<p class="result">${item}</p>`;
      })
      .join("");
    result.innerHTML = selectedText;
  } else {
    result.innerHTML = `<p class="result">${text[random]}</p>`;
  }
}

form.addEventListener("submit", generateParagraph);
